[bastionhost]
bastion-host ansible_host=130.193.43.13 ansible_user=alex

[webservers]
web1 ansible_host=192.168.10.18
web2 ansible_host=192.168.20.7

[prometheus]
prometheus-host ansible_host=192.168.20.13

[grafana]
grafana-host ansible_host=192.168.20.21

[elasticsearch]
elasticsearch-host ansible_host=192.168.20.27

[kibana]
kibana-host ansible_host=192.168.20.33

[webservers:vars]
ansible_user=alex
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q alex@130.193.43.13"'

[prometheus:vars]
ansible_user=alex
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q alex@130.193.43.13"'

[grafana:vars]
ansible_user=alex
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q alex@130.193.43.13"'

[elasticsearch:vars]
ansible_user=alex
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q alex@130.193.43.13"'

[kibana:vars]
ansible_user=alex
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q alex@130.193.43.13"'


